//@ sourceMappingURL=componentLoader.map
// Generated by CoffeeScript 1.6.0
(function() {
  var ComponentLoader,
    _this = this;

  ComponentLoader = (function() {

    ComponentLoader.wire = function(requireFun, target) {
      return new this(requireFun, target);
    };

    function ComponentLoader(_requireFun, target) {
      var _this = this;
      this._requireFun = _requireFun;
      this.component = function(pathString) {
        return ComponentLoader.prototype.component.apply(_this, arguments);
      };
      this._shortCuts = {};
      if (target != null) {
        target.component = this.component;
      }
    }

    ComponentLoader.prototype.registerShortcut = function(componentName, shortName) {
      return this._shortCuts[shortName] = componentName;
    };

    ComponentLoader.prototype.component = function(pathString) {
      var relativePath;
      if (this._shortCuts[pathString] != null) {
        pathString = this._shortCuts[pathString];
      }
      relativePath = "./" + pathString;
      return this._requireFun(relativePath);
    };

    return ComponentLoader;

  })();

  module.exports = ComponentLoader;

}).call(this);
